# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mean of a matrix (Internal use)
#'
#' @description This is an auxilliary function for internal use. It helps to
#'   numerically integrate a covariance function evaluated at a grid of points
#'   within a polyigon.
#'
#' @param mat_aux a numeric matrix.
#' @return The mean of \code{mat_aux}.
NULL

#' @title Mean of a (Matern) covariance function (Internal use)
#'
#' @description This is an auxilliary function for internal use. It helps to
#'   numerically integrate a covariance function evaluated at a grid of points
#'   within a polyigon and speed-up the computations.
#'
#' @param dists a numeric matrix representing the distance between spatial
#'   entities.
#' @param sigsq the \eqn{\sigma^2} parameter from the Matern covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Matern covariance function,
#'   controls the range of the spatial dependence.
#' @param kappa the \eqn{\kappa} parameter from the Matern covariance function,
#'   controls the differentiability of the process.
#' 
#' @return The mean of \code{mat_cov(dist, sigsq, phi, kappa)}.
NULL

#' @title Mean of a (Powered Exponential) covariance function (Internal use)
#'
#' @description This is an auxilliary function for internal use. It helps to
#'   numerically integrate a covariance function evaluated at a grid of points
#'   within a polyigon and speed-up the computations.
#'
#' @param dists a numeric matrix representing the distance between spatial
#'   entities.
#' @param sigsq the \eqn{\sigma^2} parameter from the Powered Exponential
#'   covariance function.
#' @param phi the \eqn{\phi} parameter from the Powered Exponential covariance
#'   function, controls the range of the spatial dependence.
#' @param kappa the \eqn{\kappa} parameter from the Powered Exponential
#'   covariance function,
#'   controls the differentiability of the process.
#' 
#' @return The mean of \code{pexp_cov(dist, sigsq, phi, kappa)}.
NULL

#' @title Mean of a (Gaussian) covariance function (Internal use)
#'
#' @description This is an auxilliary function for internal use. It helps to
#'   numerically integrate a covariance function evaluated at a grid of points
#'   within a polyigon and speed-up the computations.
#'
#' @param dists a numeric matrix representing the distance between spatial
#'   entities.
#' @param sigsq the \eqn{\sigma^2} parameter from the Gaussian covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Gaussian covariance function,
#'   controls the range of the spatial dependence.
#' 
#' @return The mean of \code{gauss_cov(dist, sigsq, phi)}.
NULL

#' @title Mean of a (Spherical) covariance function (Internal use)
#'
#' @description This is an auxilliary function for internal use. It helps to
#'   numerically integrate a covariance function evaluated at a grid of points
#'   within a polyigon and speed-up the computations.
#'
#' @param dists a numeric matrix representing the distance between spatial
#'   entities.
#' @param sigsq the \eqn{\sigma^2} parameter from the Spherical covariance.
#'   function.
#' @param phi the \eqn{\phi} parameter from the Spherical covariance function,
#'   controls the range of the spatial dependence.
#' 
#' @return The mean of \code{spher_cov(dist, sigsq, phi)}.
NULL

#' @title Pairwise distances between matrices
#' 
#' @description Internal use.
#'
#' @param m1 a matrix representing a grid of points within a polygon.
#' @param m2 a matrix representing a grid of points within a polygon.
#' 
crossdist <- function(m1, m2) {
    .Call(`_spmismo_crossdist`, m1, m2)
}

#' @title Matern covariance function (scalar - generic)
#'
#' @description Computing the Matern covariance function for a single distance
#'   measure, addapted from \code{\link[geoR]{matern}}.
#'
#' @param d a scalar representing the distance on which it is desired to
#'   evaluate the covariance function.
#' @param sigsq the \eqn{\sigma^2} parameter from the Matern covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Matern covariance function,
#'   controls the range of the spatial dependence.
#' @param kappa the \eqn{\kappa} parameter from the Matern covariance function,
#'   controls the differentiability of the process.
#'
#' @return a scalar representing the (matern) covariance between two
#'   observations \code{d} apart of each other.
#' 
#' @seealso \code{\link{single_matern}}, \code{\link{single_matern5}}
#'   \code{\link{single_exp}}, \code{\link{mat_cov}}
#' 
single_matern <- function(d, sigsq, phi, kappa) {
    .Call(`_spmismo_single_matern`, d, sigsq, phi, kappa)
}

#' @title Matern covariance function (scalar - kappa = 3/2)
#'
#' @description Computing the Matern covariance function for a single distance
#'   measure, with \eqn{\kappa = 3/2}.
#'
#' @param d a scalar representing the distance on which it is desired to
#'   evaluate the covariance function.
#' @param sigsq the \eqn{\sigma^2} parameter from the Matern covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Matern covariance function,
#'   controls the range of the spatial dependence.
#'
#' @return a scalar representing the (matern) covariance between two
#'   observations \code{d} apart of each other.
#' 
#' @seealso \code{\link{single_matern}}, \code{\link{single_matern5}}
#'   \code{\link{single_exp}}, \code{\link{mat_cov}}
#' 
single_matern3 <- function(d, sigsq, phi) {
    .Call(`_spmismo_single_matern3`, d, sigsq, phi)
}

#' @title Matern covariance function (scalar - kappa = 5/2)
#'
#' @description Computing the Matern covariance function for a single distance
#'   measure, with \eqn{\kappa = 5/2}.
#'
#' @param d a scalar representing the distance on which it is desired to
#'   evaluate the covariance function.
#' @param sigsq the \eqn{\sigma^2} parameter from the Matern covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Matern covariance function,
#'   controls the range of the spatial dependence.
#'
#' @return a scalar representing the (matern) covariance between two
#'   observations \code{d} apart of each other.
#' 
#' 
#' @seealso \code{\link{single_matern}}, \code{\link{single_matern3}}
#'   \code{\link{single_exp}}, \code{\link{mat_cov}}
#' 
single_matern5 <- function(d, sigsq, phi) {
    .Call(`_spmismo_single_matern5`, d, sigsq, phi)
}

#' @title Exponential covariance function (scalar)
#'
#' @description Computing the Exponential covariance function for a single
#'   distance measure.
#'
#' @param d a scalar representing the distance on which it is desired to
#'   evaluate the covariance function.
#' @param sigsq the \eqn{\sigma^2} parameter from the Exponential covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Exponential covariance function,
#'   controls the range of the spatial dependence.
#'
#' @return a scalar representing the (exponential) covariance between two
#'   observations \code{d} apart of each other.
#' 
#' 
#' @seealso \code{\link{single_pexp}}, \code{\link{single_matern}},
#'   \code{\link{single_matern3}}, \code{\link{single_matern5}},
#'   \code{\link{mat_cov}}
#' 
single_exp <- function(d, sigsq, phi) {
    .Call(`_spmismo_single_exp`, d, sigsq, phi)
}

#' @title Matern covariance function for a given distance matrix.
#'
#' @description Computing the Matern covariance function for a matrix of
#'   distances.
#'
#' @param dists a numeric matrix representing the distance between spatial
#'   entities.
#' @param sigsq the \eqn{\sigma^2} parameter from the Matern covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Matern covariance function,
#'   controls the range of the spatial dependence.
#' @param kappa the \eqn{\kappa} parameter from the Matern covariance function,
#'   controls the differentiability of the process.
#' 
#' @return The matern covariance function (for a stationary and isotropic
#'   process) associated with the provided distances (\code{dists}) and the
#'   given set of parameters.
#'
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}}
#' 
mat_cov <- function(dists, sigsq, phi, kappa) {
    .Call(`_spmismo_mat_cov`, dists, sigsq, phi, kappa)
}

#' @title Matern covariance function for a polygons.
#'
#' @description Computing the Matern covariance function between polygons.
#'
#' @param cross_dists a \code{list} such that each position contains the cross
#'   distances between points within different polygons.
#' @param n an ingeger representing number of polygons (note that, this is
#'   different than the size of the list \code{cross_dists}
#' @param n2 usually, equal to \code{n}, except when the function is being used
#'   to calculate the "cross" covariance between two different partitions of
#'   the same space.
#' @param sigsq the \eqn{\sigma^2} parameter from the Matern covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Matern covariance function,
#'   controls the range of the spatial dependence.
#' @param kappa the \eqn{\kappa} parameter from the Matern covariance function,
#'   controls the differentiability of the process. Note that, if we set
#'   \code{kappa = .5}, then the calculations are based on the exponential
#'   covariance function.
#' 
#' @return The matern covariance matrix associated with a set of polygons.
#'
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}},
#'   \code{\link{mat_cov}}
#' 
comp_mat_cov <- function(cross_dists, n, n2, sigsq, phi, kappa) {
    .Call(`_spmismo_comp_mat_cov`, cross_dists, n, n2, sigsq, phi, kappa)
}

#' @title Powered Exponential covariance function (scalar)
#'
#' @description Computing the Powered Exponential covariance function for a
#'   single distance measure.
#'
#' @param d a scalar representing the distance on which it is desired to
#'   evaluate the covariance function.
#' @param sigsq the \eqn{\sigma^2} parameter from the Exponential covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Exponential covariance function,
#'   controls the range of the spatial dependence.
#' @param kappa the \eqn{\kappa \in (0, 2]} parameter representing the "power"
#'
#' @return a scalar representing the (exponential) covariance between two
#'   observations \code{d} apart of each other.
#' 
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}},
#'   \code{\link{single_matern3}}, \code{\link{single_matern5}},
#'   \code{\link{mat_cov}}
#' 
single_pexp <- function(d, sigsq, phi, kappa) {
    .Call(`_spmismo_single_pexp`, d, sigsq, phi, kappa)
}

#' @title Powered Exponential covariance function for a given distance matrix.
#'
#' @description Computing the Matern covariance function for a matrix of
#'   distances.
#'
#' @param dists a numeric matrix representing the distance between spatial
#'   entities.
#' @param sigsq the \eqn{\sigma^2} parameter from the Exponential covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Exponential covariance function,
#'   controls the range of the spatial dependence.
#' @param kappa the \eqn{\kappa \in (0, 2]} parameter representing the "power"
#' 
#' @return The powered exponential covariance function (for a stationary and
#'   isotropic process) associated with the provided distances (\code{dists})
#'   and the given set of parameters.
#'
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}}
#' 
pexp_cov <- function(dists, sigsq, phi, kappa) {
    .Call(`_spmismo_pexp_cov`, dists, sigsq, phi, kappa)
}

#' @title Powered Exponential covariance function for a polygons.
#'
#' @description Computing the Powered Exponential covariance function between
#'   polygons.
#'
#' @param cross_dists a \code{list} such that each position contains the cross
#'   distances between points within different polygons.
#' @param n an ingeger representing number of polygons (note that, this is
#'   different than the size of the list \code{cross_dists}
#' @param n2 usually, equal to \code{n}, except when the function is being used
#'   to calculate the "cross" covariance between two different partitions of
#'   the same space.
#' @param sigsq the \eqn{\sigma^2} parameter from the Powered Exponential
#'   covariance function.
#' @param phi the \eqn{\phi} parameter from the Powered Exponential covariance
#'   function, controls the range of the spatial dependence.
#' @param kappa the \eqn{\kappa \in (0, 2]} parameter representing the "power"
#' 
#' @return The powered exponential covariance matrix associated with a set of
#'   polygons.
#'
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}},
#'   \code{\link{mat_cov}}
#' 
#' @export
comp_pexp_cov <- function(cross_dists, n, n2, sigsq, phi, kappa) {
    .Call(`_spmismo_comp_pexp_cov`, cross_dists, n, n2, sigsq, phi, kappa)
}

#' @title Gaussian covariance function (scalar)
#'
#' @description Computing the Gaussian covariance function for a single
#'   distance measure.
#'
#' @param d a scalar representing the distance on which it is desired to
#'   evaluate the covariance function.
#' @param sigsq the \eqn{\sigma^2} parameter from the Gaussian covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Gaussian covariance function,
#'   controls the range of the spatial dependence.
#'
#' @return a scalar representing the (gaussian) covariance between two
#'   observations \code{d} apart of each other.
#' 
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}},
#'   \code{\link{single_matern3}}, \code{\link{single_matern5}},
#'   \code{\link{mat_cov}}
#' 
single_gauss <- function(d, sigsq, phi) {
    .Call(`_spmismo_single_gauss`, d, sigsq, phi)
}

#' @title Computing the Gaussian covariance function for a single distance
#'   measure.
#'
#' @param dists a numeric matrix representing the distance between spatial
#'   entities.
#' @param sigsq the \eqn{\sigma^2} parameter from the Gaussian covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Gaussian covariance function,
#'   controls the range of the spatial dependence.
#'
#' @return The Gaussian covariance function (for a stationary and
#'   isotropic process) associated with the provided distances (\code{dists})
#'   and the given set of parameters.
#'
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}}
#' 
gauss_cov <- function(dists, sigsq, phi) {
    .Call(`_spmismo_gauss_cov`, dists, sigsq, phi)
}

#' @title Gaussian covariance function for a polygons.
#'
#' @description Computing the Gaussian covariance function between polygons.
#'
#' @param cross_dists a \code{list} such that each position contains the cross
#'   distances between points within different polygons.
#' @param n an ingeger representing number of polygons (note that, this is
#'   different than the size of the list \code{cross_dists}
#' @param n2 usually, equal to \code{n}, except when the function is being used
#'   to calculate the "cross" covariance between two different partitions of
#'   the same space.
#' @param sigsq the \eqn{\sigma^2} parameter from the Gaussian covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Gaussian covariance function,
#'   controls the range of the spatial dependence.
#' 
#' @return The gaussian covariance matrix associated with a set of
#'   polygons.
#'
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}},
#'   \code{\link{mat_cov}}
#' 
comp_gauss_cov <- function(cross_dists, n, n2, sigsq, phi) {
    .Call(`_spmismo_comp_gauss_cov`, cross_dists, n, n2, sigsq, phi)
}

#' @title Spherical covariance function (scalar)
#'
#' @description Computing the Spherical covariance function for a single
#'   distance measure.
#'
#' @param d a scalar representing the distance on which it is desired to
#'   evaluate the covariance function.
#' @param sigsq the \eqn{\sigma^2} parameter from the Spherical covariance.
#'   function.
#' @param phi the \eqn{\phi} parameter from the Spherical covariance function,
#'   controls the range of the spatial dependence.
#'
#' @return a scalar representing the (gaussian) covariance between two
#'   observations \code{d} apart of each other.
#' 
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}},
#'   \code{\link{single_matern3}}, \code{\link{single_matern5}},
#'   \code{\link{mat_cov}}
#' 
single_spher <- function(d, sigsq, phi) {
    .Call(`_spmismo_single_spher`, d, sigsq, phi)
}

#' @title Computing the Spherical covariance function for a single distance
#'   measure.
#'
#' @param dists a numeric matrix representing the distance between spatial
#'   entities.
#' @param sigsq the \eqn{\sigma^2} parameter from the Spherical covariance.
#'   function.
#' @param phi the \eqn{\phi} parameter from the Spherical covariance function,
#'   controls the range of the spatial dependence.
#''
#' @return The Spherical covariance function (for a stationary and
#'   isotropic process) associated with the provided distances (\code{dists})
#'   and the given set of parameters.
#'
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}}
#' 
spher_cov <- function(dists, sigsq, phi) {
    .Call(`_spmismo_spher_cov`, dists, sigsq, phi)
}

#' @title Spherical covariance function for a polygons.
#'
#' @description Computing the Spherical covariance function between polygons.
#'
#' @param cross_dists a \code{list} such that each position contains the cross
#'   distances between points within different polygons.
#' @param n an ingeger representing number of polygons (note that, this is
#'   different than the size of the list \code{cross_dists}
#' @param n2 usually, equal to \code{n}, except when the function is being used
#'   to calculate the "cross" covariance between two different partitions of
#'   the same space.
#' @param sigsq the \eqn{\sigma^2} parameter from the Spherical covariance
#'   function.
#' @param phi the \eqn{\phi} parameter from the Spherical covariance function,
#'   controls the range of the spatial dependence.
#' 
#' @return The spherical covariance matrix associated with a set of
#'   polygons.
#'
#' @seealso \code{\link{single_exp}}, \code{\link{single_matern}},
#'   \code{\link{mat_cov}}
#' 
comp_spher_cov <- function(cross_dists, n, n2, sigsq, phi) {
    .Call(`_spmismo_comp_spher_cov`, cross_dists, n, n2, sigsq, phi)
}

